version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Specify the Node.js version you need
    commands:
      - npm install

  # build:
  #   commands:
  #     - npm test

  post_build:
    commands:
      - echo $REGION
      - echo $ACCOUNT_ID
      - echo $ECR_REPO_NAME
      - echo $IMAGE_NAME

      # Build Docker image
      - docker build -t $ECR_REPO_NAME/$IMAGE_NAME .

      # Tag Docker image
      - docker tag $ECR_REPO_NAME/$IMAGE_NAME:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO_NAME:latest

      # Push Docker image to ECR
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO_NAME:latest